---
namespace: menandmice
name: ansible_micetro
version: 1.0.12
readme: README.md
authors:
  - Ton Kersten <t.kersten@atcomputing.nl>
  - Adam Brauns (@abrauns-silex)
description: Collection to manage the Men&Mice Micetro environment with Ansible
# https://www.gnu.org/licenses/gpl-3.0-standalone.html
license:
  - GPL-3.0-only
tags:
  - men_and_mice
  - micetro
  - dns
  - dhcp
  - ipam
  - ansible
  - automation
repository: https://github.com/menandmice/ansible_micetro
homepage: https://menandmice.com/
documentation: https://github.com/menandmice/ansible_micetro/
issues: https://github.com/menandmice/ansible_micetro/issues
dependencies: {}
build_ignore:
  - a
  - .tox
  - play_tests
  - docs
  - "*.tar.gz"
  - "*.tgz"
  - micetro.yml
  - ansible.cfg
  - group_vars
  - host_vars
